name: 'Generate Commit SVG'
description: 'Generates a commit percentage SVG dashboard'
author: 'Nix Ran'

inputs:
  repository:
    description: 'The repository to analyze (default: current repository)'
    required: false
    default: '.'
  branch:
    description: 'The branch to push the generated SVG to (default: commit-dashboard)'
    required: false
    default: 'commit-dashboard'
  token:
    description: 'GitHub token used for authentication'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}
  env:
    TOKEN: ${{ inputs.token }}  # Pass the token to the Docker container
